-- Conteudo inicial do roadmap "Proximas Atualizacoes", baseado no documento
-- "Instrucao para o Claude Code" que o dono do produto preparou como
-- planejamento oficial das proximas versoes do sistema. Os itens que ja
-- apareciam marcados como concluidos no documento entram como 'disponivel',
-- o resto comeca como 'planejado'. Alguns itens que o documento ainda
-- mostrava como pendente ja foram construidos em sessoes anteriores
-- (assinatura eletronica via Autentique/Assinafy, webhooks, gestao de
-- empresas e planos no Superadmin) e por isso foram marcados como
-- 'disponivel' tambem, pra nao aparecer como planejado algo que o usuario
-- ja pode usar hoje.
INSERT INTO roadmap_features (category, name, description, benefits, how_to_use, problem_solved, status, display_order) VALUES

-- Dashboard
('Dashboard', 'Resumo do Dia', 'Um resumo diário mostrando o que aconteceu na agência e o que precisa de atenção agora.', 'Você não precisa mais abrir todos os módulos pra entender o que está acontecendo, o resumo já entrega isso pronto.', 'Aparece automaticamente assim que você abre o Dashboard.', 'Hoje não existe uma visão geral rápida do dia a dia da agência.', 'disponivel', 1),
('Dashboard', 'Painel de Clientes e Campanhas', 'Um painel central que mostra de relance quantos clientes e campanhas estão ativos, quais precisam de atenção, o que está agendado pra hoje (postagens, reuniões, tarefas) e quanto do plano já foi usado.', 'Dá pra ter uma visão completa da operação sem ficar navegando entre vários menus diferentes.', 'Vai aparecer direto na tela inicial do Dashboard.', 'Hoje é preciso entrar em cada módulo separado pra montar esse quadro geral na cabeça.', 'planejado', 2),
('Dashboard', 'Central de Pendências', 'Uma lista destacada com tudo que precisa de ação imediata: erro em campanha, pixel ou conta desconectada, campanha pausada, relatório ou tarefa atrasada.', 'Nada fica passando batido, e isso evita perder dinheiro por causa de um erro que ninguém percebeu a tempo.', 'Fica numa seção fixa no topo do Dashboard.', 'Problemas silenciosos, como pixel caído ou conta desconectada, hoje só são notados quando o cliente reclama.', 'planejado', 3),
('Dashboard', 'Painel da Equipe', 'Mostra quem da equipe está online, no que cada um está trabalhando, quantos clientes atende e um ranking de produtividade.', 'Dá pra gerenciar a equipe sem precisar ficar perguntando o que cada um está fazendo.', 'Aparece no Dashboard pra quem tem colaboradores cadastrados.', 'Falta visibilidade sobre a carga de trabalho e a produtividade de cada colaborador.', 'planejado', 4),
('Dashboard', 'Resumo de Social Media no Dashboard', 'Um mini calendário de postagens direto no Dashboard, mostrando o que vai ao ar hoje e o que ainda está esperando aprovação.', 'Fica mais difícil esquecer de aprovar ou publicar um conteúdo no prazo certo.', 'Aparece num card dedicado dentro do Dashboard.', 'Hoje é preciso entrar no módulo de Social Media só pra saber se tem algo pendente.', 'planejado', 5),
('Dashboard', 'IA: Resumo Inteligente do Dia', 'A IA analisa toda a operação do dia e escreve um resumo em linguagem simples, apontando problemas, oportunidades e o que fazer a seguir.', 'Economiza o tempo de analisar tudo manualmente e ajuda a decidir mais rápido.', 'Aparece num card de IA no topo do Dashboard.', 'Analisar tudo na mão toda manhã toma um tempo considerável.', 'planejado', 6),

-- Clientes
('Clientes', 'Cadastro de Clientes', 'Cadastre, edite e remova os clientes da sua agência em poucos cliques.', 'Organiza todos os clientes num lugar só, sem depender de planilha.', 'Menu Clientes, botão Novo Cliente.', 'Antes as informações de cliente ficavam espalhadas em planilhas e conversas de WhatsApp.', 'disponivel', 1),
('Clientes', 'Histórico, Status e Etiquetas do Cliente', 'Cada cliente ganha uma linha do tempo com tudo que já aconteceu, anotações internas, status como ativo ou atrasado, etiquetas personalizadas e uma busca rápida.', 'Você não esquece mais um detalhe importante sobre o cliente.', 'Fica dentro da ficha do cliente, na aba de histórico e observações.', 'Informações importantes do cliente acabam se perdendo em conversas antigas.', 'planejado', 2),
('Clientes', 'Perfil Completo do Cliente', 'Reúne logo, site e todas as contas e ferramentas do cliente, como redes sociais, Meta Ads, Google Ads, Analytics, Tag Manager e Pixel, num único lugar.', 'Você não precisa mais procurar login ou link de uma ferramenta do cliente em outro canto.', 'Aba de dados dentro do cadastro do cliente.', 'Hoje as informações de acesso e as contas do cliente ficam espalhadas em vários lugares.', 'planejado', 3),
('Clientes', 'Arquivos do Cliente', 'Guarde contratos, criativos, vídeos, PDFs e logos de cada cliente organizados dentro do próprio cadastro dele.', 'Tudo do cliente fica num único lugar, sem precisar abrir pasta externa.', 'Aba de arquivos dentro do cadastro do cliente.', 'Os arquivos dos clientes hoje ficam espalhados em Drive, WhatsApp e e-mail.', 'planejado', 4),

-- Acompanhamento do Cliente
('Acompanhamento do Cliente', 'Crescimento (Diário, Semanal, Mensal, Anual)', 'Acompanhe a evolução dos resultados do cliente em diferentes períodos, com gráficos comparando um contra o outro.', 'Fica mais fácil enxergar de forma objetiva se o cliente está melhorando ou piorando.', 'Aba de acompanhamento dentro do cliente.', 'Hoje é difícil comparar resultados de períodos diferentes de forma rápida.', 'planejado', 1),
('Acompanhamento do Cliente', 'Métricas de Instagram e Facebook', 'Seguidores, alcance, impressões, curtidas, comentários, compartilhamentos, salvamentos e engajamento do cliente, tudo atualizado automaticamente.', 'Prova o valor do trabalho de social media sem precisar exportar relatório na mão.', 'Aba de Acompanhamento, na seção de Redes Sociais.', 'Hoje é preciso entrar direto no Instagram ou no Facebook pra ver esses números.', 'planejado', 2),
('Acompanhamento do Cliente', 'Métricas de Meta Ads e Google Ads', 'Um painel com leads, CPA, CPM, ROAS e frequência do Meta Ads, além de cliques, impressões, CTR, CPC e conversões do Google Ads.', 'Dá pra ver toda a performance paga num lugar só.', 'Aba de Acompanhamento, na seção de Tráfego Pago.', 'Hoje é preciso abrir o Gerenciador de Anúncios e o Google Ads separadamente pra juntar essa informação.', 'planejado', 3),
('Acompanhamento do Cliente', 'Métricas do Site', 'Acompanhe visitantes, sessões, conversões, tempo médio e taxa de rejeição do site do cliente.', 'Ajuda a entender se o tráfego pago está realmente gerando resultado no site.', 'Aba de Acompanhamento, seção Site, exige o Google Analytics conectado.', 'Falta visibilidade sobre o que acontece depois que a pessoa clica no anúncio.', 'planejado', 4),
('Acompanhamento do Cliente', 'IA de Análise do Cliente', 'A IA analisa os números do cliente e escreve um resumo com pontos positivos, negativos, oportunidades e um plano de ação sugerido.', 'Economiza horas de análise manual antes de uma reunião com o cliente.', 'Botão de analisar com IA, dentro da aba de Acompanhamento.', 'Analisar todos os dados na mão é demorado.', 'planejado', 5),
('Acompanhamento do Cliente', 'Modo Reunião', 'Gera automaticamente um PDF ou uma apresentação de slides pronta pra reunião com o cliente, já com comparação de períodos e plano de ação.', 'Economiza horas que hoje são gastas montando relatório ou apresentação na mão.', 'Botão de Modo Reunião, dentro da ficha do cliente.', 'Montar uma apresentação pra reunião de cliente manualmente toma bastante tempo.', 'planejado', 6),

-- Tráfego Pago
('Tráfego Pago', 'Relatórios e Alertas Automáticos', 'Relatórios automáticos enviados por WhatsApp ou e-mail, e alertas quando alguma campanha precisa de atenção.', 'Economiza o tempo de montar relatório na mão toda semana e evita que problema passe despercebido.', 'Já está ativo, configurável em Relatórios e Alertas.', 'Antes o relatório era montado manualmente toda semana.', 'disponivel', 1),
('Tráfego Pago', 'IA: Diagnóstico Automático', 'A IA já analisa e diagnostica sozinha o desempenho das campanhas.', 'Identifica o que está errado numa campanha sem precisar de análise manual.', 'Dentro do módulo de Campanhas e Tráfego Pago.', 'Identificar o que está errado numa campanha normalmente exige experiência e tempo.', 'disponivel', 2),
('Tráfego Pago', 'IA: Sugestões e Estratégias', 'Além de diagnosticar, a IA vai sugerir ações concretas, comparar campanhas entre si, explicar as métricas em linguagem simples e ajudar a planejar orçamento.', 'As decisões de otimização ficam mais rápidas e menos dependentes da experiência de quem está mexendo.', 'Vai aparecer dentro do módulo de Campanhas, ao lado do diagnóstico que já existe.', 'Saber diagnosticar o problema é uma coisa, saber o que fazer a respeito é outra bem diferente.', 'planejado', 3),

-- Social Media
('Social Media', 'Criação Manual de Postagens', 'Crie postagens completas, com imagem, vídeo, carrossel, reels ou stories, já com legenda e hashtags, direto no sistema.', 'Não precisa mais de outra ferramenta só pra montar o conteúdo.', 'Módulo Social Media, botão de Nova Postagem.', 'Hoje é preciso usar um app externo pra criar e agendar postagem.', 'planejado', 1),
('Social Media', 'Criação de Conteúdo com IA', 'A IA cria imagens, legendas, hashtags e chamadas pra ação, e consegue montar um calendário inteiro de 30 dias de conteúdo de uma vez só.', 'Você nunca mais trava sem saber o que postar, e a produção de conteúdo fica pronta em minutos.', 'Módulo Social Media, opção de criar com IA.', 'Criar conteúdo consistente todo dia é desgastante.', 'planejado', 2),
('Social Media', 'Calendário de Postagens', 'Organize todas as postagens num calendário visual mensal, arrastando pra reagendar ou duplicando um post que já funcionou bem.', 'Dá pra ver com clareza o que está agendado pra cada cliente.', 'Módulo Social Media, aba de Calendário.', 'Hoje é fácil perder o controle de quando cada coisa deveria ser postada.', 'planejado', 3),
('Social Media', 'Publicação e Aprovação', 'Publique direto no Instagram e no Facebook do cliente, com um fluxo de aprovação antes de qualquer coisa ir ao ar.', 'O cliente ou o gestor aprova antes da publicação, o que evita erro exposto publicamente.', 'Módulo Social Media, opção de Publicar.', 'Postar algo errado ou sem aprovação pode gerar um problema sério com o cliente.', 'planejado', 4),

-- Agenda
('Agenda', 'Reuniões', 'Agende reuniões ligadas a clientes e colaboradores, presenciais ou online, com anexos e observações.', 'Você nunca mais perde o controle de quando é a próxima reunião e com quem.', 'Módulo Agenda, botão de Nova Reunião.', 'Hoje as reuniões acabam marcadas em lugares diferentes, WhatsApp, e-mail ou só de cabeça.', 'planejado', 1),
('Agenda', 'Tarefas Integradas à Agenda', 'Veja e gerencie tarefas com prazo, prioridade e responsável direto na visão de calendário da Agenda.', 'Tarefa e compromisso ficam num lugar só, sem precisar trocar de tela.', 'Módulo Agenda, aba de Tarefas.', 'Hoje tarefa e reunião ficam em telas separadas.', 'planejado', 2),
('Agenda', 'Visualização de Calendário', 'Veja sua agenda em modo diário, semanal ou mensal, e reorganize compromissos arrastando com o mouse.', 'Dá pra escolher a forma mais fácil pra você enxergar sua rotina.', 'Módulo Agenda.', 'Hoje falta flexibilidade pra visualizar a rotina do jeito que cada um prefere.', 'planejado', 3),
('Agenda', 'Integrações de Calendário', 'Sincronize a Agenda do sistema com Google Agenda, Outlook ou Apple Calendar.', 'Você não precisa mais olhar dois calendários diferentes.', 'Configurações, seção de Integrações de Calendário.', 'Manter dois calendários atualizados na mão é trabalhoso.', 'planejado', 4),
('Agenda', 'IA na Agenda', 'A IA organiza sua agenda, resume reuniões automaticamente, cria tarefas a partir do que foi decidido e encontra horários livres.', 'Menos trabalho manual de organização e de follow-up depois da reunião.', 'Módulo Agenda, assistente de IA.', 'Sair de uma reunião e ter que lembrar e anotar tudo manualmente é trabalhoso.', 'planejado', 5),

-- Equipe
('Equipe', 'Cadastro de Colaboradores', 'Cadastre e gerencie os colaboradores da sua agência.', 'Dá controle sobre quem tem acesso ao sistema.', 'Menu Colaboradores.', 'Antes o acesso da equipe era dado sem nenhum controle.', 'disponivel', 1),
('Equipe', 'Gestão Avançada de Equipe', 'Defina cargos e permissões específicas, veja quais clientes cada colaborador atende, acompanhe a produtividade num ranking e use um Kanban de tarefas por pessoa.', 'Permite uma gestão de equipe mais profissional, sem depender só da palavra do colaborador.', 'Menu Equipe, seção de Gestão.', 'Hoje não dá pra saber com precisão o que cada colaborador está fazendo e produzindo.', 'planejado', 2),

-- Contratos
('Contratos', 'Geração Automática de Contrato', 'Gere contratos automaticamente a partir dos dados do cliente.', 'Elimina o trabalho de montar contrato do zero pra cada cliente novo.', 'Módulo Contratos.', 'Antes o contrato era escrito na mão pra cada cliente.', 'disponivel', 1),
('Contratos', 'Assinatura Eletrônica', 'Envie o contrato direto pra assinatura eletrônica, integrado com Autentique ou Assinafy.', 'Fecha contrato sem precisar imprimir, assinar à mão e escanear depois.', 'Módulo Contratos, opção de enviar para assinatura.', 'Antes o processo de assinatura era em papel ou por fora do sistema.', 'disponivel', 2),
('Contratos', 'Editor de Contratos e Modelos', 'Edite o texto do contrato livremente, salve como modelo reutilizável e exporte em PDF.', 'Permite personalizar o contrato sem perder a padronização.', 'Módulo Contratos, opção de Editor.', 'Hoje falta flexibilidade pra personalizar o contrato.', 'planejado', 3),
('Contratos', 'Renovação Automática de Contrato', 'Configure a renovação automática do contrato quando o prazo estiver vencendo, com histórico completo de tudo.', 'O contrato fica sempre em dia, sem correr o risco de esquecer a renovação.', 'Módulo Contratos, configuração de renovação.', 'Esquecer de renovar contrato deixa a agência sem cobertura jurídica com o cliente.', 'planejado', 4),

-- Financeiro
('Financeiro', 'Financeiro Básico', 'Controle financeiro da agência e dos clientes, com mensalidades e status de pagamento.', 'Mostra entrada e saída num lugar só.', 'Menu Financeiro.', 'Antes o financeiro era controlado numa planilha separada.', 'disponivel', 1),
('Financeiro', 'Financeiro Avançado da Agência', 'Fluxo de caixa completo, contas a pagar e a receber, cálculo de comissões, controle de inadimplência e relatórios com gráficos.', 'Dá uma visão financeira completa da agência sem depender de planilha externa.', 'Menu Financeiro, seção da Agência.', 'O financeiro da própria agência, e não só dos clientes, ainda fica espalhado em planilhas.', 'planejado', 2),

-- Biblioteca
('Biblioteca', 'Upload e Organização de Arquivos', 'Envie e organize todos os arquivos de cada cliente em pastas, categorias e tags, com busca rápida e favoritos.', 'Você nunca mais perde um arquivo importante do cliente.', 'Menu Biblioteca.', 'Hoje os arquivos ficam espalhados em Drive, WhatsApp, e-mail e pastas locais.', 'planejado', 1),
('Biblioteca', 'Biblioteca de Criativos', 'Guarde todos os criativos já produzidos pro cliente, prontos pra reaproveitar ou usar como referência.', 'Dá pra reaproveitar um criativo que já performou bem em vez de refazer do zero.', 'Menu Biblioteca, seção de Criativos.', 'Hoje é comum refazer um criativo parecido com um que já existia.', 'planejado', 2),
('Biblioteca', 'Biblioteca de Marketing e Documentos', 'Um acervo de copys, legendas, hashtags, briefings, manual da marca e todos os documentos importantes de cada cliente.', 'Tudo fica documentado e acessível pra quem for atender aquele cliente.', 'Menu Biblioteca, seção de Documentos.', 'Hoje o conhecimento sobre o cliente fica concentrado só na cabeça de quem atende.', 'planejado', 3),
('Biblioteca', 'IA na Biblioteca', 'A IA organiza os arquivos automaticamente, permite buscar por descrição em vez de nome do arquivo, e encontra duplicados.', 'Economiza o tempo de organizar arquivo manualmente.', 'Menu Biblioteca, opção de organizar com IA.', 'Organizar uma biblioteca grande de arquivos na mão é trabalhoso.', 'planejado', 4),

-- Alertas
('Alertas', 'Alertas Automáticos', 'O sistema já avisa automaticamente quando algo importante acontece nas campanhas.', 'Você fica sabendo do problema antes do cliente.', 'Menu Alertas.', 'Antes um problema só era descoberto quando o cliente reclamava.', 'disponivel', 1),
('Alertas', 'Novos Tipos de Alerta', 'Alertas específicos pra cada tipo de problema: pixel parado, conta desconectada, queda de conversão, CPA alto, ROAS baixo e orçamento acabando.', 'Reage mais rápido e de forma mais específica pra cada tipo de problema.', 'Menu Alertas, opção de Configurar.', 'Hoje os alertas são mais genéricos e não cobrem todos esses cenários.', 'planejado', 2),

-- Notificações
('Notificações', 'Central de Notificações', 'Receba notificações importantes dentro do sistema, por WhatsApp, e-mail ou push no celular.', 'Você não perde nada importante mesmo longe do computador.', 'Configurações, seção de Notificações.', 'Hoje as notificações não chegam em todos esses canais.', 'planejado', 1),

-- Configurações
('Configurações', 'Perfil e Personalização da Agência', 'Personalize seu perfil, os dados da agência, a logo exibida no sistema e o tema visual.', 'O sistema passa a ter a cara da sua agência.', 'Menu Configurações.', 'Hoje o sistema é genérico, sem identidade da agência.', 'planejado', 1),
('Configurações', 'Webhooks', 'Dispare eventos automáticos, como cliente criado, campanha atualizada ou relatório gerado, pra qualquer sistema externo via webhook.', 'Conecta o sistema com automações externas, como Zapier ou n8n, sem precisar de desenvolvimento sob medida.', 'Menu Integrações, seção de Webhooks.', 'Faltava um jeito simples de conectar o sistema com ferramentas externas.', 'disponivel', 2),
('Configurações', 'Gerenciamento de APIs', 'Configure e gerencie suas próprias chaves de API, como OpenAI, Meta, Google e Evolution, direto nas Configurações.', 'Dá mais controle e transparência sobre as integrações usadas.', 'Menu Configurações, seção de APIs.', 'Falta um lugar único pra gerenciar todas as chaves de integração.', 'planejado', 3),

-- Administração
('Administração', 'Gestão de Empresas, Planos e Assinaturas', 'Cadastro de empresas clientes, atribuição de planos (Básico, Pro, Premium) e gestão de assinaturas por cartão ou Pix.', 'Permite trazer agências novas sem trabalho manual, já com cobrança automática.', 'Painel de Superadmin, seção Empresas.', 'Antes cada cliente novo era cadastrado na mão, um por um, sem cobrança automatizada.', 'disponivel', 1),
('Administração', 'Cupons, Logs e Auditoria', 'Cupons de desconto pra assinatura, e um histórico completo de logs e auditoria de tudo que acontece no sistema.', 'Traz mais controle e rastreabilidade das ações na plataforma.', 'Painel de Superadmin.', 'Hoje falta rastreabilidade das ações administrativas.', 'planejado', 2),

-- Futuras Integrações
('Futuras Integrações', 'CRM Comercial', 'Um CRM completo pra captar e gerenciar novos clientes em potencial da própria agência, antes mesmo de fecharem contrato.', 'Organiza o processo comercial da agência, não só a entrega do serviço em si.', 'Novo módulo de CRM, ainda por vir.', 'A prospecção de clientes novos hoje é feita sem nenhuma ferramenta dedicada.', 'planejado', 1),
('Futuras Integrações', 'Portal do Cliente', 'Uma área exclusiva onde o próprio cliente da agência acompanha os resultados da campanha dele, sem precisar pedir relatório.', 'Traz mais transparência com o cliente final e menos trabalho de ficar respondendo como estão os resultados.', 'Login separado pro cliente final, ainda por vir.', 'Hoje o cliente final não tem acesso direto aos próprios resultados.', 'planejado', 2),
('Futuras Integrações', 'Aplicativo para Android e iPhone', 'Um aplicativo nativo pra usar o sistema direto do celular.', 'Dá acesso rápido de qualquer lugar, sem precisar abrir o navegador.', 'Vai estar disponível na loja de aplicativos quando for lançado.', 'Usar o sistema pelo navegador do celular não é tão prático.', 'planejado', 3),
('Futuras Integrações', 'Atendimento via WhatsApp', 'Atendimento de clientes direto pelo WhatsApp, já integrado ao sistema.', 'Centraliza o atendimento sem precisar sair da plataforma.', 'Novo módulo de Atendimento, ainda por vir.', 'Hoje o atendimento ao cliente acontece fora do sistema, sem registro.', 'planejado', 4),
('Futuras Integrações', 'API Pública', 'Uma API pública pra outros sistemas se conectarem à plataforma.', 'Abre a possibilidade de integrar com outras ferramentas usadas pela agência.', 'Vai ficar em Configurações, seção de Desenvolvedores, quando estiver pronta.', 'Hoje não é possível integrar um sistema externo com a plataforma.', 'planejado', 5),
('Futuras Integrações', 'Marca Branca para Outras Agências', 'Permite que outras agências usem o sistema com a própria marca, logo, cores e domínio.', 'Abre um novo modelo de negócio de licenciamento da plataforma.', 'Vai ser contratado como um plano White Label, quando estiver disponível.', 'Hoje o sistema só existe com a marca Digital Alpha.', 'planejado', 6),
('Futuras Integrações', 'Backup Automático e Histórico de Alterações', 'Backup automático de todos os dados e um histórico de tudo que já foi alterado no sistema.', 'Traz uma camada extra de segurança contra perda de dados.', 'Roda automaticamente, nos bastidores.', 'Hoje falta um backup dedicado e rastreável.', 'planejado', 7);
