name: Deploy Staging to Production

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Merged to production
        run: echo "Deploy realizado em produção com sucesso!"
